Main/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path
from django.conf.urls import url, include

app_name = 'Main'

urlpatterns = [

                  path('admin/', admin.site.urls),
                  url(r'^accounting/', include('accounting.urls')),
                  url(r'^twitting/', include('twitting.urls')),
                  url(r'^paging/', include('paging.urls')),
                  url(r'^froalaImage/', include('froalaImaging.urls')),
                  url(r'^home/', include('homeservice.urls')),
                  url(r'^liking/', include('liking.urls')),
                  url(r'^following/', include('following.urls')),
                  url(r'^channeling/', include('channelling.urls')),
                  url(r'^alerting/', include('alerting.urls')),
                  url(r'^seach/', include('searchengine.urls')),
                  url(r'^confirming/', include('confirming.urls')),
              ] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT) + static(settings.STATIC_URL,
                                                                                         document_root=settings.STATIC_ROOT)

accounting/urls.py
# account/urls.py
from django.conf.urls import url
from django.urls import path

from accounting import views


app_name = 'accounting'
# Be careful setting the name to just /login use userlogin instead!
urlpatterns = [
    url(r'^signup/$', views.signup_view, name='signup'),
    url(r'^login/$', views.login_view, name='login'),
    path('activate/<str:username>/<str:code>', views.activate, name='activate'),
    path('profile/<str:username>', views.profile_view, name='profile'),
    path('reset/<str:code>', views.reset_password_view, name='reset-password'),
    url(r'^logout/', views.logout_view, name='logout'),
    url(r'^edit/$', views.edit_profile, name='edit'),
    url(r'^forgot/$', views.forget_password_view, name='forgot'),
    url(r'^myprofile/$', views.my_profile, name='my-profile')
]

accounting/models.py
from django.contrib.auth.models import User
from django.db import models


class Account(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE, default=None, related_name="account")
    portfolio_site = models.URLField(default='google.com', blank=True, null=True)
    profile_photo = models.FileField(null=True, upload_to="profiles", default='/profiles/default.png')
    name = models.CharField(max_length=20, blank=False)
    location = models.TextField(max_length=60, default='iran!', null=True)
    bio = models.TextField(max_length=120, default='nothing until now')

    def __str__(self):
        return self.name

accounting/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm, UserChangeForm
from django.contrib.auth.models import User
from accounting.models import Account


class SignUpForm(UserCreationForm):
    email = forms.EmailField(max_length=150, help_text='Email')

    class Meta:
        model = User
        fields = ('username', 'email', 'password1', 'password2',)

accounting/views.py
import json
from django.contrib.auth import login, authenticate, logout
from django.contrib.auth.decorators import login_required
from django.contrib.auth.models import User
from django.contrib.sites.shortcuts import get_current_site
from django.core.mail import send_mail
from django.http import Http404, HttpResponse
from django.shortcuts import render, redirect
from django.template.loader import render_to_string
from django.utils.html import strip_tags

from confirming.models import ConfirmRequest
from tokenManager.models import TokenManager
from following.models import Follow
from paging.models import Page
from searchengine.models import DocIndex
from .forms import SignUpForm
from .models import Account


def login_view(request):
    if request.method == 'POST':
        username = request.POST.get('username')
        password = request.POST.get('password')

        q = User.objects.filter(username=username)

        if q.exists():
            user = q.get()
            if user.is_active:
                user = authenticate(request, username=username, password=password)
                if user:
                    login(request, user)
                    return redirect('homeservice:home')
                else:
                    errors = {
                        'password': 'incorrect password'
                    }
            else:
                errors = {
                    'authentication': 'check your email to activate your account!'
                }
        else:
            errors = {
                'invalid_user': "Invalid login details given"
            }
    else:
        errors = {}
    return render(request, 'accounting/login.html', {'errors': json.dumps(errors)})


def activate(request, username, code):
    token = TokenManager.objects.filter(username=username, code=code, type='activate').first()
    if token is not None:
        user = User.objects.filter(username=username).first()
        user.is_active = True
        user.save()

        account = Account(user=user)
        account.user = user
        account.name = str(user.username)
        account.save()

        personal_page = Page(personal_page=True, title=user.username + ' page', creator=account,
                             page_id=account.user.username)
        personal_page.save()
        personal_page.admins.add(account)
        personal_page.save()

        token.delete()

        DocIndex.add_doc(username, username, 'user')

        return render(request, 'accounting/activate_done.html')
    else:
        errors = {
            'token': 'invalid token code for activation'
        }
        return render(request, 'accounting/login.html', {'errors': json.dumps(errors)})


def signup_view(request):
    if request.method == 'POST':
        form = SignUpForm(request.POST)
        if form.is_valid():
            user = form.save()
            user.refresh_from_db()
            user.is_active = False
            user.save()

            current_site = get_current_site(request)
            mail_subject = 'Activate your account.'
            token = TokenManager.create_new_token(username=user.username, type='activate')
            token.save()
            data = {
                'user': user,
                'domain': current_site.domain,
                'token': token.code,
            }
            message = render_to_string('accounting/activation_page.html', data)
            print(message)
            text_content = strip_tags(message)
            to_email = form.cleaned_data.get('email')
            send_mail(mail_subject, text_content, 'joorabnakhi@gmail.com', [to_email])

            return render(request, 'accounting/activation_sent.html')
        else:
            return render(request, 'accounting/signup.html', {'form': form, 'errors': json.dumps(form.errors)})
    else:
        form = SignUpForm()
        return render(request, 'accounting/signup.html', {'form': form})


def logout_view(request):
    logout(request)
    return redirect('/home')


def get_profile_page(request, owner):
    setting = request.user == owner
    followed = False
    if request.user.is_authenticated:
        if Follow.objects.filter(followed=owner.account, follower=request.user.account):
            followed = True
    followers = Follow.objects.filter(followed=owner.account)
    followings = Follow.objects.filter(follower=owner.account)
    page = Page.objects.filter(creator=owner.account, personal_page=True).get()
    can_view = page.can_view(request.user)
    is_owner = request.user == owner
    confirm_requests = []
    if is_owner:
        confirm_requests = ConfirmRequest.objects.filter(channel=page)
    data = {'owner': owner, 'setting': setting, 'followed': followed, 'followers': followers,
            'followings': followings, 'can_view': can_view, 'is_owner': is_owner, 'confirm_requests': confirm_requests}
    return render(request, 'accounting/profile.html', data)


@login_required
def my_profile(request):
    return get_profile_page(request, request.user)


def profile_view(request, username):
    owner = User.objects.filter(username=username).first()
    if owner:
        return get_profile_page(request, owner)
    else:
        return HttpResponse(status=404)


@login_required
def edit_profile(request):
    public = Page.objects.filter(creator=request.user.account, personal_page=True).get().public
    errors = []
    if request.POST:
        if request.FILES:
            try:
                request.user.account.profile_photo = request.FILES.get('profile_photo')
                request.user.account.save()
            except:
                errors.append('cant load image!')
        try:
            username = request.POST.get('username')
            name = request.POST.get('name')
            email = request.POST.get('email')
            location = request.POST.get('location')
            bio = request.POST.get('bio')
            public = str(request.POST.get('public')) == 'on'
        except:
            errors.append('bad format of data')
        if username:
            if str(request.user.username) != str(username):
                if User.objects.filter(username=username):
                    errors.append('this username is token by others ...')
                else:
                    page = Page.objects.get(page_id=request.user.username)
                    page.page_id = username
                    page.save()
                    request.user.username = username
                    request.user.save()

        if location and bio and email and name:
            account = request.user.account
            account.bio = bio
            request.user.email = email
            account.location = location
            account.name = name
            account.save()
            request.user.save()
            page = Page.objects.filter(creator=account, personal_page=True).get()
            page.public = public
            page.save()

        DocIndex.add_doc(bio, request.user.username, 'user')
        DocIndex.add_doc(name, request.user.username, 'user')
        DocIndex.add_doc(username, request.user.username, 'user')
        DocIndex.add_doc(location, request.user.username, 'user')

        request.user.save()
        request.user.account.save()
    return render(request, 'accounting/profile_edit.html', {'errors': json.dumps(errors), 'public': public})


def forget_password_view(request):
    if request.POST:
        username = request.POST.get('username')
        if not User.objects.filter(username=username).exists():
            return HttpResponse(status=404)
        user = User.objects.get(username=username)
        token = TokenManager.create_new_token(username, 'reset')
        token.save()
        mail_subject = 'forget password'
        text = 'http://localhost:8000/accounting/reset/' + token.code
        send_mail(mail_subject, text, 'joorabnakhi@gmail.com', [user.email])
        return redirect('accounting:login')
    return render(request, 'accounting/forgot_password.html')


def reset_password_view(request, code):
    if request.POST:
        pass1 = request.POST.get('password1')
        pass2 = request.POST.get('password2')

        if str(pass1) != str(pass2):
            return redirect('accounting:reset-password', code)
        if not TokenManager.objects.filter(code=code).exists():
            return HttpResponse(status=404)
        token = TokenManager.objects.get(code=code, type='reset')
        user = User.objects.filter(username='s').get()
        user.set_password(pass1)
        user.save()
        token.delete()
        return redirect('accounting:login')

    return render(request, 'accounting/reset_password.html', {'token': code})

templates/accounting/activate_done.html
<h3>Activation was done. Now you can login to your account.</h3>

<a href="{% url 'accounting:login' %}"><h1 style="color: red">Login</h1></a>

templates/accounting/activation_invalid.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>In valid</title>
</head>
<body>

</body>
</html>

templates/accounting/activation_page.html
<h4>welcome to Twigger!</h4>
<p>Hi {{ user.username }}</p>
<h6 style="color: #a94442">click this to activate your account.</h6>
<a class="btn btn-block btn-success btn-lg font-weight-medium"
   href="/accounting/activate/{{ user.username }}/{{ token }}"><h1
        style="color: red">{{ domain }}/accounting/activate/{{ user.username }}/{{ token }}</h1></a>

templates/accounting/activation_request.html
{% autoescape off %}
    Hi {{ user.username }},

    Please click the following link to confirm your registration:

    <a href="/accounting/activate/{{ user.username }}/{{ token }}">Activate!</a>
{% endautoescape %}

templates/accounting/activation_sent.html
<h3>Activation link sent! Please check your console or mail.</h3>

templates/accounting/base.html
<!DOCTYPE html>
<html lang="en">
<head>

{# semantic #}
    <script src="https://code.jquery.com/jquery-3.1.1.min.js" crossorigin="anonymous"></script>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/semantic-ui@2.4.2/dist/semantic.min.css">
    <script src="https://cdn.jsdelivr.net/npm/semantic-ui@2.4.2/dist/semantic.min.js"></script>


    <meta charset="UTF-8">
    {% block head %}
    {% endblock %}
</head>
<body>
{% block body %}
{% endblock %}
</body>
</html>

templates/accounting/login.html
{% extends 'base.html' %}

{% block head %}
    {% load static %}
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <title>Login</title>
    <link rel="stylesheet" href={% static 'vendors/mdi/css/materialdesignicons.min.css' %}>
    <link rel="stylesheet" href={% static 'vendors/base/vendor.bundle.base.css' %}>
    <link rel="stylesheet" href={% static 'css/style.css' %}>

    <style>
        .background-image {
            position: fixed;
            top: 0;
            bottom: 0;
            right: 0;
            left: 0;
            height: 100%;
            width: 100%;
            z-index: 0;
            background-image: url("{% static '9401.jpg' %}");
            background-repeat: no-repeat;
            background-size: cover;
        }
    </style>
{% endblock %}

{% block body %}


    <div class="background-image">
    </div>


    <div class="container-scroller">
        <div class="container-fluid page-body-wrapper full-page-wrapper">
            <div class="main-panel">
                <div class="content-wrapper d-flex align-items-center auth px-0">
                    <div class="row w-100 mx-0">
                        <div class="col-lg-4 mx-auto">

                            <div class="auth-form-transparent text-left p-3">
                                <div class="brand-logo">
                                </div>
                                <h4>Welcome back!</h4>
                                <h6 class="font-weight-light">Happy to see you again!</h6>
                                <form class="pt-3" method="post" action="{% url 'accounting:login' %}">
                                    {% csrf_token %}
                                    <div class="form-group">
                                        <label for="exampleInputEmail">Username</label>
                                        <div class="input-group">
                                            <div class="input-group-prepend bg-transparent">`
                                                <span class="input-group-text bg-transparent border-right-0">
                        <i class="mdi mdi-account-outline text-primary"></i>
                      </span>
                                            </div>
                                            <input name="username" type="text"
                                                   class="form-control form-control-lg border-left-0"
                                                   id="exampleInputEmail" placeholder="Username">
                                        </div>
                                    </div>
                                    <div class="form-group">
                                        <label for="exampleInputPassword">Password</label>
                                        <div class="input-group">
                                            <div class="input-group-prepend bg-transparent">
                      <span class="input-group-text bg-transparent border-right-0">
                        <i class="mdi mdi-lock-outline text-primary"></i>
                      </span>
                                            </div>
                                            <input type="password" name="password"
                                                   class="form-control form-control-lg border-left-0"
                                                   id="exampleInputPassword" placeholder="Password">
                                        </div>
                                    </div>
                                    <div class="my-2 d-flex justify-content-between align-items-center">
                                        <div class="form-check">
                                            <label class="form-check-label text-muted">
                                                <input type="checkbox" class="form-check-input">
                                                Keep me signed in
                                            </label>
                                        </div>
                                        <a href="#" class="auth-link text-black">Forgot password?</a>
                                    </div>
                                    <div class="my-3">
                                        <button class="btn btn-block btn-primary btn-lg font-weight-medium auth-form-btn">
                                            LOGIN
                                        </button>
                                    </div>
                                    <div class="mb-2 d-flex">
                                        <button type="button" class="btn btn-google auth-form-btn flex-grow">
                                            <i class="mdi mdi-google mr-2"></i>Google
                                        </button>
                                    </div>
                                    <div class="text-center mt-4 font-weight-light">
                                        Don't have an account? <a
                                            href={% url 'accounting:signup' %} class="text-primary">Create</a>
                                    </div>
                                    <div class="text-center mt-4 font-weight-light">
                                        forget password? <a
                                            href={% url 'accounting:forgot' %} class="text-primary">forget</a>
                                    </div>
                                </form>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
    </div>


    <script src="{% static 'Errors.js' %}"></script>
    <script>
        let errors = JSON.parse('{{ errors | escapejs }}');
        console.log(errors);
        show_errors(errors);

    </script>

{% endblock %}

templates/accounting/profile.html
{% extends 'base.html' %}

{% block head %}
    {% load static %}

    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <title> Professionals Resume HTML Bootstrap Template | Smarteyeapps.com</title>

    <link rel="shortcut icon" href="{% static 'profile-files/images/fav.jpg' %}">
    <link rel="stylesheet" href="{% static 'profile-files/css/bootstrap.min.css' %}">
    <link rel="stylesheet" href="{% static 'profile-files/css/fontawsom-all.min.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'profile-files/css/style.css' %}"/>

    <style>
        .background-image {
            position: fixed;
            top: 0;
            bottom: 0;
            right: 0;
            left: 0;
            height: 100%;
            width: 100%;
            z-index: -999;
            background-image: url("{% static '9401.jpg' %}");
            background-repeat: no-repeat;
            background-size: cover;
        }
    </style>

{% endblock %}

{% block body %}

    <div class="background-image">
    </div>

    <div class="container-fluid overcover">
        <div class="container profile-box">
            <div class="top-cover" style="height: fit-content;">
                <div class="covwe-inn">
                    <div class="row no-margin">
                        <div class="col-md-3 img-c">
                            <img src="{{ owner.account.profile_photo.url }}" alt="">
                        </div>
                        <div class="col-md-9 tit-det">
                            <h2>{{ owner.account.name }}</h2>

                        </div>
                    </div>
                </div>
            </div>
            <ul class="nav nav-tabs" id="myTab" role="tablist">
                <li class="nav-item">
                    <a class="nav-link active" id="home-tab" data-toggle="tab" href="#home" role="tab"
                       aria-controls="home"
                       aria-selected="true">Profile</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" id="profile-tab" data-toggle="tab" href="#profile" role="tab"
                       aria-controls="profile" aria-selected="false">Followers</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" id="profile-tab" data-toggle="tab" href="#resume" role="tab"
                       aria-controls="profile"
                       aria-selected="false">Following</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" id="profile-tab" data-toggle="tab" href="#gallery" role="tab"
                       aria-controls="profile" aria-selected="false">Portfolio</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" id="contact-tab" data-toggle="tab" href="#contact" role="tab"
                       aria-controls="contact" aria-selected="false">Contact</a>
                </li>
            </ul>
            <div class="tab-content" id="myTabContent">
                <div class="tab-pane fade show active" id="home" role="tabpanel" aria-labelledby="home-tab">
                    <div class="row no-margin home-det">
                        <div class="col-md-4 big-img">

                            <h3 class="ltitle">Info</h3>

                            <div class="refer-cov">
                                <p><b>username:</b> {{ owner.username }}</p>
                                <br>
                                <p><b>name:</b> {{ owner.account.name }}</p>
                                <br>
                                <p><b>location:</b> {{ owner.account.location }}</p>
                            </div>
                            <div class="refer-cov">

                                <p><b>accessibility: </b> {% if owner.account.is_private %}Private{% else %}
                                    Public{% endif %}</p>
                            </div>

                        </div>
                        <div class="col-md-8 home-dat">
                            <h2 class="rit-titl"> Bio
                            </h2>
                            <p>{{ owner.account.bio }}</p>
                            <div class="links">
                                <div class="row ">
                                    <div class="col-xl-6 col-md-12">
                                        <ul class="btn-link">
                                            {% if can_view %}
                                                <a href="{% url 'view_page' owner.username %}">
                                                    <button class="green ui toggle button">View page</button>
                                                </a>
                                            {% endif %}
                                            {% if request.user.is_authenticated %}
                                                <a href="{% url 'follow-page' owner.username %}">
                                                    <button class="{% if followed %}red{% else %}green{% endif %} ui active button">
                                                        <i class=" user icon"></i>{% if followed %}Unfollow{% else %}
                                                        Follow{% endif %}
                                                    </button>
                                                </a>
                                            {% endif %}
                                            {% if setting %}
                                                <a href="{% url 'accounting:edit' %}">
                                                    <button class="ui icon button">
                                                        <i class=" cog white icon"></i>
                                                    </button>
                                                </a>
                                            {% endif %}
                                        </ul>
                                    </div>

                                </div>
                            </div>
                        </div>

                    </div>
                </div>
                <div class="tab-pane fade exp-cover" id="profile" role="tabpanel" aria-labelledby="profile-tab">
                    <div class="data-box">
                        <div class="sec-title">
                            <h2>Followers</h2>
                        </div>
                        {% for follower in followers %}
                            <div class="row exp-row">
                                <h6>{{ follower.follower.name }}</h6>
                                <a href="{% url 'accounting:profile' follower.follower.user.username %}"><span>{{ follower.follower.user.username }}</span></a>

                                <p>{{ follower.follower.bio }}</p>
                            </div>
                        {% endfor %}


                        {% if is_owner %}
                            <ul>
                                {% for confirm_request in confirm_requests %}
                                    <li>
                                        <div class="ui compact message">
                                            <p>{{ confirm_request.account.name }} want to follow this channel.</p>
                                            <div class="ui buttons">
                                                <a href="{% url 'decline' owner.username confirm_request.account.user.username %}">
                                                    <button class="ui red button">Decline</button>
                                                </a>
                                                <div class="or"></div>
                                                <a href="{% url 'confirm' owner.username confirm_request.account.user.username %}">
                                                    <button class="ui positive button">Confirm</button>
                                                </a>
                                            </div>
                                        </div>
                                    </li>
                                {% endfor %}
                            </ul>
                        {% endif %}


                    </div>
                </div>
                <div class="tab-pane fade exp-cover" id="resume" role="tabpanel" aria-labelledby="contact-tab">

                    <div class="data-box">
                        <div class="sec-title">
                            <h2>Following</h2>
                        </div>
                        {% for following in followings %}
                            <div class="row exp-row">
                                <h6>{{ following.followed.name }}</h6>
                                <a href="{% url 'accounting:profile' following.followed.user.username %}"><span>{{ following.followed.user.username }}</span></a>

                                <p>{{ following.followed.bio }}</p>
                            </div>
                        {% endfor %}
                    </div>


                </div>
                <div class="tab-pane fade gallcoo" id="gallery" role="tabpanel" aria-labelledby="contact-tab">
                    <div class="row no-margin gallery">


                    </div>
                </div>
                <div class="tab-pane fade contact-tab" id="contact" role="tabpanel" aria-labelledby="contact-tab">
                    <div class="row no-margin">
                        <div class="col-md-6 no-padding">
                            <iframe src="https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d3176144.0450019627!2d-107.79423426090409!3d38.97644533805396!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x874014749b1856b7%3A0xc75483314990a7ff!2sColorado%2C+USA!5e0!3m2!1sen!2sin!4v1547222354537"
                                    frameborder="0" style="border:0" allowfullscreen></iframe>
                        </div>
                        <div class="col-md-6">
                            <div class="row cont-row no-margin">
                                <div class="col-sm-6">
                                    <input placeholder="Enter Full Name" type="text"
                                           class="form-control form-control-sm">
                                </div>
                                <div class="col-sm-6">
                                    <input placeholder="Enter Email Address" type="text"
                                           class="form-control form-control-sm">
                                </div>
                            </div>
                            <div class="row cont-row no-margin">
                                <div class="col-sm-6">
                                    <input placeholder="Enter Mobile Number" type="text"
                                           class="form-control form-control-sm">
                                </div>

                            </div>
                            <div class="row cont-row no-margin">
                                <div class="col-sm-12">
                                <textarea placeholder="Enter your Message" class="form-control form-control-sm"
                                          rows="10"></textarea>
                                </div>

                            </div>
                            <div class="row cont-row no-margin">
                                <div class="col-sm-6">
                                    <button class="btn btn-sm btn-primary">Send Message</button>
                                </div>

                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>

    {% load static %}

    <script src="{% static 'profile-files/js/jquery-3.2.1.min.js' %}"></script>
    <script src="{% static 'profile-files/js/popper.min.js' %}"></script>
    <script src="{% static 'profile-files/js/bootstrap.min.js' %}"></script>
    <script src="{% static 'profile-files/js/script.js' %}"></script>


{% endblock %}