Main/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path
from django.conf.urls import url, include

app_name = 'Main'

urlpatterns = [

                  path('admin/', admin.site.urls),
                  url(r'^accounting/', include('accounting.urls')),
                  url(r'^twitting/', include('twitting.urls')),
                  url(r'^paging/', include('paging.urls')),
                  url(r'^froalaImage/', include('froalaImaging.urls')),
                  url(r'^home/', include('homeservice.urls')),
                  url(r'^liking/', include('liking.urls')),
                  url(r'^following/', include('following.urls')),
                  url(r'^channeling/', include('channelling.urls')),
                  url(r'^alerting/', include('alerting.urls')),
                  url(r'^seach/', include('searchengine.urls')),
                  url(r'^confirming/', include('confirming.urls')),
              ] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT) + static(settings.STATIC_URL,
                                                                                         document_root=settings.STATIC_ROOT)

accounting/urls.py
# account/urls.py
from django.conf.urls import url
from django.urls import path

from accounting import views


app_name = 'accounting'
# Be careful setting the name to just /login use userlogin instead!
urlpatterns = [
    url(r'^signup/$', views.signup_view, name='signup'),
    url(r'^login/$', views.login_view, name='login'),
    path('activate/<str:username>/<str:code>', views.activate, name='activate'),
    path('profile/<str:username>', views.profile_view, name='profile'),
    path('reset/<str:code>', views.reset_password_view, name='reset-password'),
    url(r'^logout/', views.logout_view, name='logout'),
    url(r'^edit/$', views.edit_profile, name='edit'),
    url(r'^forgot/$', views.forget_password_view, name='forgot'),
    url(r'^myprofile/$', views.my_profile, name='my-profile')
]

searchengine/urls.py
from django.urls import path
from django.conf.urls import url, include

app_name = 'searchengin'

from searchengine import views

urlpatterns = [
    path('', views.search, name='search')
]

templates/searchengin/search.html
{% extends 'base.html' %}

{% block head %}
    {% load static %}

    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <link rel="shortcut icon" href="{% static 'profile-files/images/fav.jpg' %}">
    <link rel="stylesheet" href="{% static 'profile-files/css/bootstrap.min.css' %}">
    <link rel="stylesheet" href="{% static 'profile-files/css/fontawsom-all.min.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'profile-files/css/style.css' %}"/>

    <style>
        .background-image {
            position: fixed;
            top: 0;
            bottom: 0;
            right: 0;
            left: 0;
            height: 100%;
            width: 100%;
            z-index: -999;
            background-image: url("{% static '9401.jpg' %}");
            background-repeat: no-repeat;
            background-size: cover;
        }
    </style>

{% endblock %}

{% block body %}

    <div class="background-image">
    </div>

    <form method="post" action="{% url 'searchengin:search' %}" class="ui form">
        {% csrf_token %}
        <div class="field">
            <label>Search</label>
            <div class="ui selection dropdown">
                <div class="ui icon input">
                    <input class="prompt" type="text" placeholder="Search all docs" name="words">
                    <i class="search icon"></i>
                </div>
            </div>
        </div>
    </form>


    {% for result in results %}
        <div class="ui success message">
            <i class="close icon"></i>
            {{ result.type }}
            <br><br>
            <div class="header">
                {{ result.key }}
            </div>
            <p>
                {{ result.word }}
            </p>

            {% if result.type == 'user' %}
                <a href="{% url 'accounting:profile' result.value %}">click to see</a>
            {% endif %}
            {% if result.type == 'tweet' %}
                <a href="{% url 'view_tweet' result.value %}">click to see</a>
            {% endif %}
            {% if result.type == 'page' %}
                <a href="{% url 'view_page' result.value %}">click to see</a>
            {% endif %}

        </div>
    {% endfor %}

    {% load static %}

    <script src="{% static 'profile-files/js/jquery-3.2.1.min.js' %}"></script>
    <script src="{% static 'profile-files/js/popper.min.js' %}"></script>
    <script src="{% static 'profile-files/js/bootstrap.min.js' %}"></script>
    <script src="{% static 'profile-files/js/script.js' %}"></script>


{% endblock %}