Main/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path
from django.conf.urls import url, include

app_name = 'Main'

urlpatterns = [

                  path('admin/', admin.site.urls),
                  url(r'^accounting/', include('accounting.urls')),
                  url(r'^twitting/', include('twitting.urls')),
                  url(r'^paging/', include('paging.urls')),
                  url(r'^froalaImage/', include('froalaImaging.urls')),
                  url(r'^home/', include('homeservice.urls')),
                  url(r'^liking/', include('liking.urls')),
                  url(r'^following/', include('following.urls')),
                  url(r'^channeling/', include('channelling.urls')),
                  url(r'^alerting/', include('alerting.urls')),
                  url(r'^seach/', include('searchengine.urls')),
                  url(r'^confirming/', include('confirming.urls')),
              ] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT) + static(settings.STATIC_URL,
                                                                                         document_root=settings.STATIC_ROOT)

accounting/urls.py
# account/urls.py
from django.conf.urls import url
from django.urls import path

from accounting import views


app_name = 'accounting'
# Be careful setting the name to just /login use userlogin instead!
urlpatterns = [
    url(r'^signup/$', views.signup_view, name='signup'),
    url(r'^login/$', views.login_view, name='login'),
    path('activate/<str:username>/<str:code>', views.activate, name='activate'),
    path('profile/<str:username>', views.profile_view, name='profile'),
    path('reset/<str:code>', views.reset_password_view, name='reset-password'),
    url(r'^logout/', views.logout_view, name='logout'),
    url(r'^edit/$', views.edit_profile, name='edit'),
    url(r'^forgot/$', views.forget_password_view, name='forgot'),
    url(r'^myprofile/$', views.my_profile, name='my-profile')
]

alerting/urls.py
from django.conf.urls import url
from django.urls import path

from alerting import views

app_name = 'alerting'

urlpatterns = [
    url(r'^notifies/', views.notifies, name='notifies'),
    path('seen/<int:id>', views.seen_alert, name='seen')
]

channelling/urls.py
# account/urls.py
from django.conf.urls import url
from django.urls import path

from channelling import views

app_name = 'channelling'
# Be careful setting the name to just /login use userlogin instead!
urlpatterns = [
    url(r'^new-channel/', views.new_channel, name='new-channel'),
    path(r'edit-channel/<str:page_id>', views.edit_chanel, name='edit-channel'),
    path('channel/<str:page_id>', views.channel_view, name='channel'),
    path('add-admin/<str:page_id>', views.add_admin, name='add-admin'),
    path('remove-admin/<str:page_id>', views.remove_admin, name='remove-admin'),

]

homeservice/urls.py
from django.conf.urls import url
from homeservice import views

app_name = 'homeservice'

urlpatterns = [
    url('', views.homepage, name='home'),
]

templates/base.html
<!DOCTYPE>
<html>
<head>
    <meta charset="utf-8">

    <!-- semantic -->
    <script src="https://code.jquery.com/jquery-3.1.1.min.js" crossorigin="anonymous"></script>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/semantic-ui@2.4.2/dist/semantic.min.css">
    <script src="https://cdn.jsdelivr.net/npm/semantic-ui@2.4.2/dist/semantic.min.js"></script>


    <!-- forala -->
    <link href='https://cdn.jsdelivr.net/npm/froala-editor@3.1.0/css/froala_editor.pkgd.min.css' rel='stylesheet'
          type='text/css'/>
    <script type='text/javascript'
            src='https://cdn.jsdelivr.net/npm/froala-editor@3.1.0/js/froala_editor.pkgd.min.js'></script>


    <!-- sweet alert -->
    <script src="https://cdn.jsdelivr.net/npm/sweetalert2@9"></script>

    <!-- ajax -->
    <script src="https://code.jquery.com/jquery-3.1.0.min.js"></script>

    <style>

        .fixed-top-bar {
            margin: 0;
            z-index: 999999;
            position: fixed;
            top: 0;
            width: 100%;
            height: 8%;
            color: white;
            text-align: center;
            background-color: rgba(115, 142, 210, 0.26);
            box-shadow: 0 0 4px 0 rgba(0, 0, 0, 0.2), 0 20px 20px 0 rgba(0, 0, 0, 0.19);
        }

        {% load static %}


        .top-bar-right {
            float: right;
            width: auto;
            height: 100%;
        }

        .top-bar-left {
            float: left;
            width: auto;
            height: 100%;
        }

        .top-bar-child {
            width: auto;
            height: 100%;
            align-items: center;
            display: flex;
        }

        body {
            width: 100%;
            height: 100%;
            background-color: rgba(220, 230, 255, 0.56);
            margin: 0 auto;
        }

        .icon-container {
            margin: 10px;
        }

        .strong-nav-item {
            padding: 8px;
            font-weight: bold
        }

    </style>

    {% block head %}

    {% endblock %}

</head>

<body>
<nav class="fixed-top-bar ">
    <div class="top-bar-right top-bar-child">

        <div class="icon-container">
            {% if request.user.is_authenticated %}
                <a href="{% url 'channelling:new-channel' %}"><i title="New channel" class="plus icon blue large"></i></a>
                <a href="{% url 'accounting:my-profile' %}"><i class="link blue user icon large"
                                                               title="Profile"></i></a>
            {% else %}

                <a href="{% url 'accounting:login' %}"><i class="link blue sign-in icon large" title="Login"></i></a>
            {% endif %}
        </div>

        <div class="icon-container">
            <a href="{% url 'homeservice:home' %}"><i class="link blue home icon large" title="Home"></i></a>
        </div>

        {% if request.user.is_authenticated %}
            <div class="icon-container">
                <a href="{% url 'my_page' %}"><i class="link blue dochub icon large" title="My page"></i></a>
            </div>
            <div class="icon-container">
                <a href="{% url 'accounting:logout' %}"><i class="link blue sign-out icon large" title="Logout"></i></a>
            </div>
        {% endif %}

    </div>


    <div class="top-bar-left top-bar-child">
        <div class="icon-container">
            <a href="{% url 'alerting:notifies' %}"><i title="Notifies" class="link blue bell outline icon large"></i></a>
        </div>

        <div class="icon-container">
            <i class="link blue envelope open outline icon large"></i>
        </div>


        <div class="blue ui fluid category search">
            <div class="ui icon input">
                <a title="Search" href="{% url 'searchengin:search' %}"><i class="blue large search icon"></i></a>
            </div>
            <div class="results"></div>
        </div>

    </div>
</nav>

<script>
    var csrf = '{% csrf_token %}';
    let j = 1;
    let a, b;
    for (let i = 0; i < csrf.length; i++) {
        if (csrf[i] === '=') {
            if (j < 3) {
                j++;
            } else {
                a = i + 1;
            }
        }
    }
    for (i = a + 1; i < csrf.length; i++) {
        if (csrf[i] === '"') {
            b = i;
        }
    }
    let str = [];
    for (let i = a + 1; i < b; i++) {
        str.push(csrf[i]);
    }
    window.csrf = str.join('');
</script>
<div style="width: 100%; height: 8%;">
</div>
{% block body %}



{% endblock %}
</body>
</html>

templates/home.html
{% extends 'base.html' %}
{% load static %}
{% block head %}
    {% load static %}
    <link rel="stylesheet" href="{% static 'twitter/twitter.css' %}">
    <style>

        * {
            box-sizing: border-box;
        }

        /* Create three equal columns that floats next to each other */
        .column {
            float: left;
            width: 30.33%;
            padding: 10px;
            height: 300px; /* Should be removed. Only for demonstration */
            background-color: transparent;
            margin: 10px;
        }

        /* Clear floats after the columns */
        .row:after {
            content: "";
            display: table;
            clear: both;
        }

        .new-account {
            color: #59608b;
            font-size: 20px;
            margin-top: 50px;
        }

        .new-account:hover {
            color: #bac6ff;
        }


        .background-image {
            position: fixed;
            top: 0;
            bottom: 0;
            right: 0;
            left: 0;
            height: 100%;
            width: 100%;
            z-index: -999999;
            background-image: url("{% static '3811.jpg' %}");
            background-position: center;
            background-repeat: no-repeat;
            background-size: cover;
        }

        .top-content {
            display: flex;
            height: 100%;
        }

        .description {
            color: #9dbbd2;
            padding: 20px;
            position: absolute;
            bottom: 0;
            float: bottom;
            width: 100%;
            background: rgb(0, 0, 0); /* Fallback color */
            background: rgba(0, 0, 0, 0.5); /* Black background with 0.5 opacity */
        }


        .big-name {
            font-weight: bold;
            font-size: 50px;
            color: #9dbbd2;
            margin-left: auto;
            margin-right: auto;
            margin-top: 20vh;
            display: table;
        }
    </style>

{% endblock %}



{% block body %}

    <div class="background-image">
    </div>

    <div class="top-content">
        <div class="big-name">
            Twigger
            <br>
            <br>
            <br>
            <a class="new-account" href="{% url 'accounting:signup' %}">Create New Account</a>
        </div>
        <div class="description">
            <h1 style="font-size: 40px">Twigger</h1>
            <h2 style="line-height: 2">
                Twigger is a cloud-based instant messaging and voice over IP service. Twigger client apps are available
                for
                Android, iOS, Windows Phone, Windows NT, macOS and Linux. Users can send messages and exchange photos,
                videos, stickers, audio and files of any type.
            </h2>
        </div>

    </div>


    <h2 style="color: deepskyblue">All accounts</h2>
    <div class="ui link cards">
        {% for account in accounts %}
            <div class="card">
                <div class="image">
                    <a href="{% url 'accounting:profile' account.user.username %}">
                        <img src="{{ account.profile_photo.url }}">
                    </a>

                </div>
                <div class="content">
                    <div class="header">{{ account.name }}</div>
                    <div class="meta">
                        <span>{{ account.user.username }}</span>
                    </div>
                </div>
                <div class="extra content">
      <span class="right floated">
        Joined in 2013
      </span>
                    <span>
        <i class="user icon"></i>
        {{ account.bio }}
      </span>
                </div>
            </div>
        {% endfor %}

    </div>


    <h2 style="color: deepskyblue">All Channels</h2>
    <div class="ui link cards">
        {% for channel in channels %}
            <div class="card">
                <div class="image">
                    <a href="{% url 'channelling:channel' channel.page_id %}">
                        <img src="https://encrypted-tbn0.gstatic.com/images?q=tbn%3AANd9GcTxZhR7oRk7coQZoOLmnMy_QZUfW6waEmvWj13jpLd4fxbQky4P">
                    </a>

                </div>
                <div class="content">
                    <div class="header">{{ channel.title }}</div>
                    <div class="meta">
                        {{ channel.description }}
                    </div>
                </div>
                <div class="extra content">
      <span class="right floated">
        Joined in 2013
      </span>
                    <span>
        <i class="user icon"></i>
            {{ channel.description }}
      </span>
                </div>
            </div>
        {% endfor %}

    </div>



    <div class="row">
        <div class="column">
            <div class="followings-tweets-list">
                <h2 style="color: deepskyblue">Tweets of your followings</h2>
                {% for followings_user_tweet in followings_users_tweets %}
                    <div class="tw-block-parent">
                        <div class="timeline-TweetList-tweet">
                            <div class="timeline-Tweet">
                                <div class="timeline-Tweet-brand">
                                    <div class="Icon Icon--twitter"></div>
                                </div>
                                <div class="timeline-Tweet-author">
                                    <div class="TweetAuthor">
                                        <span class="TweetAuthor-name">{{ followings_user_tweet.name }}</span>
                                        <span class="TweetAuthor-screenName">new post </span>
                                    </div>
                                </div>
                                <div class="timeline-Tweet-text">
                                    <a href="{% url 'view_tweet' followings_user_tweet.origin_id %}">
                                        <p>
                                            {{ followings_user_tweet.plain_text }}
                                        </p>
                                    </a>
                                </div>

                                <div class="timeline-Tweet-metadata"><span class="timeline-Tweet-timestamp">9h</span>
                                </div>
                            </div>
                        </div>
                    </div>
                    <br>

                {% endfor %}
            </div>
        </div>
        <div class="column">
            <div class="most-liked-tweets-list">
                <h2 style="color: deepskyblue">Most liked tweets of this month</h2>
                {% for most_liked_tweet in most_liked_tweets %}

                    <div class="tw-block-parent">
                        <div class="timeline-TweetList-tweet">
                            <div class="timeline-Tweet">
                                <div class="timeline-Tweet-brand">
                                    <div class="Icon Icon--twitter"></div>
                                </div>
                                <div class="timeline-Tweet-author">
                                    <div class="TweetAuthor">
                                        <span class="TweetAuthor-name">{{ most_liked_tweet.name }}</span>
                                        <span class="TweetAuthor-screenName">liked by&nbsp;{{ most_liked_tweet.like_number }}&nbsp
                                    <i class="heart red ui icon"></i></span>
                                    </div>
                                </div>
                                <div class="timeline-Tweet-text">
                                    <a href="{% url 'view_tweet' most_liked_tweet.origin_id %}">
                                        <p>
                                            {{ most_liked_tweet.plain_text }}
                                        </p>
                                    </a>
                                </div>
                                <div class="timeline-Tweet-metadata"><span class="timeline-Tweet-timestamp">{{ most_liked_tweet.time }}</span>
                                </div>
                            </div>
                        </div>
                    </div>

                    <br>

                {% endfor %}
            </div>
        </div>
        <div class="column">
            <div class="followings-tweets-list">
                <h2 style="color: deepskyblue">Tweets of your followings pages</h2>
                {% for followings_page_tweet in following_pages_tweets %}
                    <div class="tw-block-parent">
                        <div class="timeline-TweetList-tweet">
                            <div class="timeline-Tweet">
                                <div class="timeline-Tweet-brand">
                                    <div class="Icon Icon--twitter"></div>
                                </div>
                                <div class="timeline-Tweet-author">
                                    <div class="TweetAuthor">
                                        <span class="TweetAuthor-name">{{ followings_page_tweet.name }}</span>
                                        <span class="TweetAuthor-screenName">new post </span>
                                    </div>
                                </div>
                                <div class="timeline-Tweet-text">
                                    <a href="{% url 'view_tweet' followings_page_tweet.origin_id %}">
                                        <p>
                                            {{ followings_page_tweet.plain_text }}
                                        </p>
                                    </a>
                                </div>

                                <div class="timeline-Tweet-metadata"><span class="timeline-Tweet-timestamp">9h</span>
                                </div>
                            </div>
                        </div>
                    </div>
                    <br>

                {% endfor %}
            </div>
        </div>
    </div>

{% endblock %}

templates/login.html
{% extends 'base.html' %}

{% block head %}
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Login Page - Dashboard Admin Template</title>
    <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Open+Sans:300,400,600">
    <!-- https://fonts.google.com/specimen/Open+Sans -->
    {% load static %}
    <link rel="stylesheet" href={% static 'css/fontawesome.min.css' %}>
    <!-- https://fontawesome.com/ -->
    <link rel="stylesheet" href={% static 'css/bootstrap.min.css' %}>
    <!-- https://getbootstrap.com/ -->
    <link rel="stylesheet" href={% static 'css/tooplate.css' %}>
{% endblock %}

{% block body %}
    <div class="container">
        <div class="row tm-mt-big">
            <div class="col-12 mx-auto tm-login-col">
                <div class="bg-white tm-block" style="background: rgba(100,100,100,0.1)">
                    <div class="row">
                        <div class="col-12 text-center">
                            <i class="fas fa-3x fa-tachometer-alt tm-site-icon text-center"></i>
                            <h2 class="tm-block-title mt-3">Login</h2>
                            <i class="sign-in icon"></i>
                        </div>
                    </div>
                    <div class="row mt-2">
                        <div class="col-12">
                            <form action="index.html" method="post" class="tm-login-form">
                                <div class="input-group">
                                    <label for="username" class="col-xl-4 col-lg-4 col-md-4 col-sm-5 col-form-label">Username</label>
                                    <input name="username" type="text"
                                           class="form-control validate col-xl-9 col-lg-8 col-md-8 col-sm-7"
                                           id="username"
                                           value="admin" required>
                                </div>
                                <div class="input-group mt-3">
                                    <label for="password" class="col-xl-4 col-lg-4 col-md-4 col-sm-5 col-form-label">Password</label>
                                    <input name="password" type="password" class="form-control validate" id="password"
                                           value="1234" required>
                                </div>
                                <div class="input-group mt-3">
                                    <button type="submit" class="btn btn-primary d-inline-block mx-auto">Login</button>
                                </div>
                                <div class="input-group mt-3">
                                </div>
                            </form>
                            <a href={% url 'sign_up' %}>sign up</a>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <footer class="row tm-mt-big">
            <div class="col-12 font-weight-light text-center">
            </div>
        </footer>
    </div>
{% endblock %}

templates/sign_up.html
{% extends 'base.html' %}

{% block head %}
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Login Page - Dashboard Admin Template</title>
    <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Open+Sans:300,400,600">
    <!-- https://fonts.google.com/specimen/Open+Sans -->
    {% load static %}
    <link rel="stylesheet" href={% static 'css/fontawesome.min.css' %}>
    <!-- https://fontawesome.com/ -->
    <link rel="stylesheet" href={% static 'css/bootstrap.min.css' %}>
    <!-- https://getbootstrap.com/ -->
    <link rel="stylesheet" href={% static 'css/tooplate.css' %}>

    <style>
    .input-group{
        margin-top: 20px;
    }
    </style>
{% endblock %}

{% block body %}
    <div class="container">
        <div class="row tm-mt-big">
            <div class="col-12 mx-auto tm-login-col">
                <div class="bg-white tm-block" style="background: rgba(100,100,100,0.1)">
                    <div class="row">
                        <div class="col-12 text-center">
                            <i class="fas fa-3x fa-tachometer-alt tm-site-icon text-center"></i>
                            <h2 class="tm-block-title mt-3">Sign up</h2>
                            <i class="plus icon"></i>
                        </div>
                    </div>
                    <div class="row mt-2">
                        <div class="col-12">
                            <form class="tm-login-form" action="{% url 'sign_up' %}" method="post">
                                {% csrf_token %}
                                <div class="input-group">
                                    <label for="username" class="col-xl-4 col-lg-4 col-md-4 col-sm-5 col-form-label">Username</label>
                                    <input name="username" type="text"
                                           class="form-control validate col-xl-9 col-lg-8 col-md-8 col-sm-7"
                                           id="username"
                                           value="admin" required>
                                </div>
                                <div class="input-group">
                                    <label for="email" class="col-xl-4 col-lg-4 col-md-4 col-sm-5 col-form-label">Email</label>
                                    <input name="email" type="email"
                                           class="form-control validate col-xl-9 col-lg-8 col-md-8 col-sm-7"
                                           id="email"
                                           value="admin" required>
                                </div>
                                <div class="input-group mt-3">
                                    <label for="password" class="col-xl-4 col-lg-4 col-md-4 col-sm-5 col-form-label">Password</label>
                                    <input name="password1" type="password" class="form-control validate" id="password1"
                                           value="1234" required>
                                </div>
                                <div class="input-group mt-3">
                                    <label for="Confirm password" class="col-xl-4 col-lg-4 col-md-4 col-sm-5 col-form-label">Confirm password</label>
                                    <input name="password2" type="password" class="form-control validate" id="password2"
                                           value="1234" required>
                                </div>
                                <div class="input-group mt-3">
                                    <button type="submit" class="btn btn-primary d-inline-block mx-auto">Sign up</button>
                                </div>
                                <div class="input-group mt-3">
                                </div>
                            </form>
                            <a href={% url 'login' %}>login</a>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <footer class="row tm-mt-big">
            <div class="col-12 font-weight-light text-center">
            </div>
        </footer>
    </div>
{% endblock %}