Main/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path
from django.conf.urls import url, include

app_name = 'Main'

urlpatterns = [

                  path('admin/', admin.site.urls),
                  url(r'^accounting/', include('accounting.urls')),
                  url(r'^twitting/', include('twitting.urls')),
                  url(r'^paging/', include('paging.urls')),
                  url(r'^froalaImage/', include('froalaImaging.urls')),
                  url(r'^home/', include('homeservice.urls')),
                  url(r'^liking/', include('liking.urls')),
                  url(r'^following/', include('following.urls')),
                  url(r'^channeling/', include('channelling.urls')),
                  url(r'^alerting/', include('alerting.urls')),
                  url(r'^seach/', include('searchengine.urls')),
                  url(r'^confirming/', include('confirming.urls')),
              ] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT) + static(settings.STATIC_URL,
                                                                                         document_root=settings.STATIC_ROOT)

accounting/urls.py
# account/urls.py
from django.conf.urls import url
from django.urls import path

from accounting import views


app_name = 'accounting'
# Be careful setting the name to just /login use userlogin instead!
urlpatterns = [
    url(r'^signup/$', views.signup_view, name='signup'),
    url(r'^login/$', views.login_view, name='login'),
    path('activate/<str:username>/<str:code>', views.activate, name='activate'),
    path('profile/<str:username>', views.profile_view, name='profile'),
    path('reset/<str:code>', views.reset_password_view, name='reset-password'),
    url(r'^logout/', views.logout_view, name='logout'),
    url(r'^edit/$', views.edit_profile, name='edit'),
    url(r'^forgot/$', views.forget_password_view, name='forgot'),
    url(r'^myprofile/$', views.my_profile, name='my-profile')
]

channelling/urls.py
# account/urls.py
from django.conf.urls import url
from django.urls import path

from channelling import views

app_name = 'channelling'
# Be careful setting the name to just /login use userlogin instead!
urlpatterns = [
    url(r'^new-channel/', views.new_channel, name='new-channel'),
    path(r'edit-channel/<str:page_id>', views.edit_chanel, name='edit-channel'),
    path('channel/<str:page_id>', views.channel_view, name='channel'),
    path('add-admin/<str:page_id>', views.add_admin, name='add-admin'),
    path('remove-admin/<str:page_id>', views.remove_admin, name='remove-admin'),

]

channelling/models.py
from django.db import models

# Create your models here.

channelling/views.py
import json

from django.contrib.auth.decorators import login_required
from django.contrib.auth.models import User
from django.http import HttpResponse
from django.shortcuts import render, redirect

from confirming.models import ConfirmRequest
from following.models import FollowPage
from paging.models import Page
from searchengine.models import DocIndex


@login_required
def new_channel(request):
    errors = []
    if request.POST:
        id = request.POST.get('id')
        title = request.POST.get('title')
        public = str(request.POST.get('public')) == 'on'
        print(public)
        description = request.POST.get('description')
        if Page.objects.filter(page_id=id).exists():
            errors.append('this id is token by others...')
        else:
            page = Page(title=title, page_id=id, description=description, personal_page=False,
                        creator=request.user.account, public=public)
            page.save()
            page.admins.add(request.user.account)
            page.save()

            DocIndex.add_doc(title, page.page_id, 'page')
            DocIndex.add_doc(description, page.page_id, 'page')

            return redirect('channelling:channel', page.page_id)
    return render(request, 'channelling/new_channeling.html', {'errors': json.dumps(errors)})


def channel_view(request, page_id):
    q = Page.objects.filter(page_id=page_id)
    if q.exists():
        channel = q.get()
        admins = channel.admins.all()
        is_admin = False
        if request.user and request.user.is_authenticated:
            for admin in admins:
                if admin.id is request.user.account.id:
                    is_admin = True
                    break

        followed = False
        if request.user and request.user.is_authenticated:
            if FollowPage.objects.filter(follower=request.user.account, followed__page_id=page_id).exists():
                followed = True

        follows = FollowPage.objects.filter(followed__page_id=page_id)
        followers = []
        for follow in follows:
            followers.append(follow.follower)
        confirm_requests = ConfirmRequest.objects.filter(channel__page_id=page_id)
        can_view = channel.can_view(request.user)

        data = {'channel': channel, 'admins': admins, 'is_admin': is_admin, 'page_id': channel.page_id,
                'followed': followed, 'followers': followers, 'confirm_requests': confirm_requests,
                'can_view': can_view}

        return render(request, 'channelling/channel.html', data)
    else:
        return HttpResponse(status=404)


@login_required
def edit_chanel(request, page_id):
    if request.POST:
        q = Page.objects.filter(page_id=page_id)
        if not q.exists():
            return HttpResponse(status=404)
        page = q.get()

        if not page.is_this_admin(request.user.account):
            return HttpResponse(starus=404)

        public = str(request.POST.get('public')) == 'on'
        title = request.POST.get('title')
        description = request.POST.get('description')
        page.description = description
        page.title = title
        page.public = public
        page.save()
        return channel_view(request, page_id)
    return HttpResponse(status=404)


@login_required()
def add_admin(request, page_id):
    if request.POST:
        username = request.POST.get('username')
        page = Page.objects.get(page_id=page_id)
        if page.creator.id is not request.user.account.id:
            return HttpResponse(status=404)
        if not User.objects.filter(username=username):
            return redirect('channelling:channel', page_id)
        user = User.objects.get(username=username)
        page.admins.add(user.account)
        return redirect('channelling:channel', page_id)
    else:
        return HttpResponse(status=404)


@login_required()
def remove_admin(request, page_id):
    if request.POST:
        username = request.POST.get('username')
        page = Page.objects.get(page_id=page_id)
        if page.creator.id is not request.user.account.id:
            return HttpResponse(status=404)
        if not User.objects.filter(username=username):
            return redirect('channelling:channel', page_id)
        user = User.objects.get(username=username)
        page.admins.remove(user.account)
        return redirect('channelling:channel', page_id)
    else:
        return HttpResponse(status=404)

templates/channelling/channel.html
{% extends 'base.html' %}

{% block head %}
    {% load static %}

    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <title> Professionals Resume HTML Bootstrap Template | Smarteyeapps.com</title>

    <link rel="shortcut icon" href="{% static 'profile-files/images/fav.jpg' %}">
    <link rel="stylesheet" href="{% static 'profile-files/css/bootstrap.min.css' %}">
    <link rel="stylesheet" href="{% static 'profile-files/css/fontawsom-all.min.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'profile-files/css/style.css' %}"/>

    <style>
        .background-image {
            position: fixed;
            top: 0;
            bottom: 0;
            right: 0;
            left: 0;
            height: 100%;
            width: 100%;
            z-index: -999;
            background-image: url("{% static '9401.jpg' %}");
            background-repeat: no-repeat;
            background-size: cover;
        }
    </style>

{% endblock %}

{% block body %}

    <div class="background-image">
    </div>

    <div class="container-fluid overcover">
        <div class="container profile-box">
            <div class="top-cover" style="height: fit-content;">
                <div class="covwe-inn">
                    <div class="row no-margin">
                        <div class="col-md-3 img-c">
                            {#                            <img src="{{ owner.account.profile_photo.url }}" alt="">#}
                        </div>
                        <div class="col-md-9 tit-det">
                            <h2>{{ channel.title }}</h2>

                        </div>
                    </div>
                </div>
            </div>
            <ul class="nav nav-tabs" id="myTab" role="tablist">
                <li class="nav-item">
                    <a class="nav-link active" id="home-tab" data-toggle="tab" href="#home" role="tab"
                       aria-controls="home"
                       aria-selected="true">Info</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" id="profile-tab" data-toggle="tab" href="#profile" role="tab"
                       aria-controls="profile" aria-selected="false">Admins</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" id="profile-tab" data-toggle="tab" href="#resume" role="tab"
                       aria-controls="profile"
                       aria-selected="false">Members</a>
                </li>
                {% if is_admin %}
                    <li class="nav-item">
                        <a class="nav-link" id="profile-tab" data-toggle="tab" href="#gallery" role="tab"
                           aria-controls="profile" aria-selected="false">Edit</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" id="contact-tab" data-toggle="tab" href="#contact" role="tab"
                           aria-controls="contact" aria-selected="false">Admin Manager</a>
                    </li>
                {% endif %}
            </ul>
            <div class="tab-content" id="myTabContent">
                <div class="tab-pane fade show active" id="home" role="tabpanel" aria-labelledby="home-tab">
                    <div class="row no-margin home-det">
                        <div class="col-md-4 big-img">

                            <h3 class="ltitle">Info</h3>

                            <div class="refer-cov">
                                <p><b>title:</b> {{ channel.title }}</p>
                                <br>
                                <p><b>owner:</b> {{ channel.creator.name }}</p>
                                <br>
                                <p><b>description:</b> {{ channel.description }}</p>
                            </div>
                            <div class="refer-cov">

                                <p><b>accessibility: </b> {% if cahnnel.public %}Public{% else %}
                                    Private{% endif %}</p>
                            </div>

                        </div>
                        <div class="col-md-8 home-dat">

                        {% if can_view %}
                            <a href="{% url 'view_page' channel.page_id %}">
                                <button class="green ui toggle button">View page</button>
                            </a>
                        {% endif %}

                            {% if request.user.is_authenticated %}
                                <a href="{% url 'follow-page' page_id %}">
                                    <button class="{% if followed %}red{% else %}green{% endif %} ui active button">
                                        <i class=" user icon"></i>{% if followed %}Unfollow{% else %}
                                        Follow{% endif %}
                                    </button>
                                </a>
                            {% endif %}

                            <br><br>
                            <h2 class="rit-titl"> Description
                            </h2>
                            <p>{{ channel.description }}</p>
                            <div class="links">
                                <div class="row ">
                                    <div class="col-xl-6 col-md-12">
                                    </div>

                                </div>
                            </div>
                        </div>

                    </div>
                </div>
                <div class="tab-pane fade exp-cover" id="profile" role="tabpanel" aria-labelledby="profile-tab">
                    <div class="data-box">
                        <div class="sec-title">
                            <h2>Admins</h2>
                        </div>
                        {% for admin in admins %}
                            <div class="row exp-row">
                                <h6>{{ admin.name }}</h6>
                                <a href="{% url 'accounting:profile' admin.user.username %}"><span>{{ admin.user.username }}</span></a>
                                <p>{{ admin.bio }}</p>
                            </div>
                        {% endfor %}
                    </div>
                </div>
                <div class="tab-pane fade exp-cover" id="resume" role="tabpanel" aria-labelledby="contact-tab">

                    <div class="data-box">
                        <div class="sec-title">
                            <h2>Members</h2>
                        </div>
                        {% for follower in followers %}
                            <div class="row exp-row">
                                <h6>{{ follower.name }}</h6>
                                <a href="{% url 'accounting:profile' follower.user.username %}"><span>{{ follower.user.username }}</span></a>

                                <p>{{ follower.bio }}</p>
                            </div>
                        {% endfor %}
                        {% if is_admin %}
                            <ul>
                                {% for confirm_request in confirm_requests %}
                                    <li>
                                        <div class="ui compact message">
                                            <p>{{ confirm_request.account }} want to follow this channel.</p>
                                            <div class="ui buttons">
                                                <a href="{% url 'decline' page_id confirm_request.account.user.username %}">
                                                    <button class="ui red button">Decline</button>
                                                </a>
                                                <div class="or"></div>
                                                <a href="{% url 'confirm' page_id confirm_request.account.user.username %}">
                                                    <button class="ui positive button">Confirm</button>
                                                </a>
                                            </div>
                                        </div>
                                    </li>
                                {% endfor %}
                            </ul>
                        {% endif %}
                    </div>
                </div>
                {% if is_admin %}
                    <div class="tab-pane fade gallcoo" id="gallery" role="tabpanel" aria-labelledby="contact-tab">
                        <div class="row no-margin gallery">
                            <form class="ui form" method="post"
                                  action="{% url 'channelling:edit-channel' channel.page_id %}">
                                {% csrf_token %}
                                <div class="field">
                                    <label>Title</label>
                                    <input type="text" name="title" placeholder="Title" value="{{ channel.title }}">
                                </div>
                                <div class="field">
                                    <label>Description</label>
                                    <input type="text" name="description" placeholder="Description"
                                           value="{{ channel.description }}">
                                </div>
                                <div class="field">
                                    <div class="inline field">
                                        <div class="ui toggle checkbox">
                                            <input type="checkbox" name="public" checked>
                                            <label>Public channel</label>
                                        </div>
                                    </div>
                                </div>
                                <button class="ui button" type="submit">Submit</button>
                            </form>
                        </div>
                    </div>
                    <div class="tab-pane fade contact-tab" id="contact" role="tabpanel" aria-labelledby="contact-tab">
                        <div class="row no-margin">
                            <form class="ui form" method="post"
                                  action="{% url 'channelling:add-admin' channel.page_id %}">
                                {% csrf_token %}
                                <div class="field">
                                    <label>Username</label>
                                    <input type="text" name="username" placeholder="Username">
                                </div>
                                <button class="ui green button" type="submit">Add</button>
                            </form>
                            <p></p>
                            <form class="ui form" method="post"
                                  action="{% url 'channelling:remove-admin' channel.page_id %}">
                                {% csrf_token %}
                                <div class="field">
                                    <label>Username</label>
                                    <input type="text" name="username" placeholder="Username">
                                </div>
                                <button class="ui red button" type="submit">Remove</button>
                            </form>
                        </div>
                    </div>
                {% endif %}
            </div>
        </div>
    </div>

    {% load static %}

    <script src="{% static 'profile-files/js/jquery-3.2.1.min.js' %}"></script>
    <script src="{% static 'profile-files/js/popper.min.js' %}"></script>
    <script src="{% static 'profile-files/js/bootstrap.min.js' %}"></script>
    <script src="{% static 'profile-files/js/script.js' %}"></script>



{% endblock %}

templates/channelling/new_channeling.html
{% extends 'base.html' %}

{% block head %}
    {% load static %}
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <title>Edit Profile</title>
    <link rel="stylesheet" href={% static 'vendors/mdi/css/materialdesignicons.min.css' %}>
    <link rel="stylesheet" href={% static 'vendors/base/vendor.bundle.base.css' %}>
    <link rel="stylesheet" href={% static 'css/style.css' %}>

    <style>
        .background-image {
            position: fixed;
            top: 0;
            bottom: 0;
            right: 0;
            left: 0;
            height: 100%;
            width: 100%;
            z-index: 0;
            background-image: url("{% static '9401.jpg' %}");
            background-repeat: no-repeat;
            background-size: cover;
        }


    </style>
{% endblock %}

{% block body %}

    <div class="background-image">
    </div>


    <div class="container-scroller">

        <div class="container-fluid page-body-wrapper full-page-wrapper">
            <div class="main-panel">
                <div class="content-wrapper d-flex align-items-center auth px-0">
                    <div class="row w-100 mx-0">
                        <div class="col-lg-4 mx-auto">
                            <div class="brand-logo">
                            </div>
                            <h4> Edit your profile here</h4>
                            <form class="pt-3" method="post" enctype="multipart/form-data"
                                  action="{% url 'channelling:new-channel' %}">
                                {% csrf_token %}
                                <div class="form-group">
                                    <label>Title</label>
                                    <div class="input-group">
                                        <div class="input-group-prepend bg-transparent">
                      <span class="input-group-text bg-transparent border-right-0">
                        <i class="mdi mdi-account-outline text-primary"></i>
                      </span>
                                        </div>
                                        <input type="text" name="title"
                                               class="form-control form-control-lg border-left-0"
                                               placeholder="Title"
                                               value="title">
                                    </div>
                                </div>
                                <div class="form-group">
                                    <label>ID</label>
                                    <div class="input-group">
                                        <div class="input-group-prepend bg-transparent">
                      <span class="input-group-text bg-transparent border-right-0">
                        <i class="mdi mdi-account-outline text-primary"></i>
                      </span>
                                        </div>
                                        <input type="text" name="id"
                                               class="form-control form-control-lg border-left-0"
                                               placeholder="ID"
                                               value="id">
                                    </div>
                                </div>
                                <div class="form-group">
                                    <label>Description</label>
                                    <div class="input-group">
                                        <div class="input-group-prepend bg-transparent">
                      <span class="input-group-text bg-transparent border-right-0">
                        <i class="mdi mdi-account-outline text-primary"></i>
                      </span>
                                        </div>
                                        <input type="text" name="description"
                                               class="form-control form-control-lg border-left-0"
                                               placeholder="Description"
                                               value="">
                                    </div>
                                </div>

                                <div class="form-group">
                                    <div class="ui form">
                                        <div class="inline field">
                                            <div class="ui toggle checkbox">
                                                <input type="checkbox" name="public" checked>
                                                <label>Public channel</label>
                                            </div>
                                        </div>
                                    </div>
                                </div>

                                <div class="mt-3">
                                    <button class="btn btn-block btn-primary btn-lg font-weight-medium auth-form-btn">
                                        Create new channel
                                    </button>
                                </div>
                            </form>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <!-- content-wrapper ends -->
    </div>
    <!-- page-body-wrapper ends -->
    </div>

    {{ user.username }}

    <script src="{% static 'Errors.js' %}"></script>
    <script>
        let errors = JSON.parse('{{ errors | escapejs }}');
        show_errors(errors);

    </script>
{% endblock %}